# fly.toml app configuration file generated for polished-breeze-9783 on 2023-10-27T12:52:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-breeze-9783"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
